# Generated by Django 5.1.5 on 2025-02-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('employer', 'صاحب عمل'), ('manager', 'مدير')], max_length=20, verbose_name='نوع المستخدم')),
                ('subscription_type', models.CharField(choices=[('basic', 'أساسي'), ('silver', 'فضي'), ('gold', 'ذهبي')], max_length=20, verbose_name='نوع الاشتراك')),
                ('first_name', models.CharField(max_length=255, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=255, verbose_name='اسم العائلة')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة')),
                ('message', models.TextField(blank=True, null=True, verbose_name='الرسالة')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تمت معالجته؟')),
            ],
            options={
                'verbose_name': 'طلب اشتراك',
                'verbose_name_plural': 'طلبات الاشتراك',
            },
        ),
    ]
