# Generated by Django 5.2 on 2025-06-12 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('main_facility', 'Main Facility'), ('branch_facility', 'Branch Facility'), ('modify_data', 'Modify Data')], help_text='Type of service request (e.g., main_facility, branch_facility, modify_data).', max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_profile', models.TextField(blank=True, help_text='Optional: Brief description of the company profile.', max_length=2000, null=True)),
                ('agreement', models.BooleanField(default=False, help_text='Indicates if the user has agreed to terms and conditions.')),
                ('licenses', models.FileField(blank=True, help_text='Optional: Upload relevant licenses (PDF, DOCX, PNG, JPG, JPEG).', null=True, upload_to='service_requests/licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'png', 'jpg', 'jpeg'])])),
                ('managers', models.FileField(blank=True, help_text='Optional: Upload documents related to managers (PDF, DOCX, PNG, JPG, JPEG).', null=True, upload_to='service_requests/managers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'png', 'jpg', 'jpeg'])])),
                ('balance', models.FileField(blank=True, help_text='Conditionally Optional: Balance sheet (PDF, DOCX, PNG, JPG, JPEG).', null=True, upload_to='service_requests/balance/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'png', 'jpg', 'jpeg'])])),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', editable=False, help_text='Current status of the service request.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
