# Generated by Django 5.2 on 2025-06-13 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب خدمة', 'verbose_name_plural': 'طلبات الخدمة'},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_description',
            field=models.TextField(blank=True, help_text='اختياري: وصف الخدمة التي تم اختيارها من بطاقة الخدمة.', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_title',
            field=models.CharField(blank=True, help_text='اختياري: عنوان الخدمة التي تم اختيارها من بطاقة الخدمة.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='agreement',
            field=models.BooleanField(default=False, help_text='يشير إلى ما إذا كان المستخدم قد وافق على الشروط والأحكام.'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='balance',
            field=models.FileField(blank=True, help_text='اختياري مشروط: الميزانية العمومية (PDF, DOCX, PNG, JPG, JPEG).', null=True, upload_to='service_requests/balance/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='company_profile',
            field=models.TextField(blank=True, help_text='اختياري: وصف موجز لملف تعريف الشركة.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='licenses',
            field=models.FileField(blank=True, help_text='اختياري: قم بتحميل التراخيص ذات الصلة (PDF, DOCX, PNG, JPG, JPEG).', null=True, upload_to='service_requests/licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='managers',
            field=models.FileField(blank=True, help_text='اختياري: قم بتحميل المستندات المتعلقة بالمديرين (PDF, DOCX, PNG, JPG, JPEG).', null=True, upload_to='service_requests/managers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('main_facility', 'المنشأة الرئيسية'), ('branch_facility', 'المنشأة الفرعية'), ('modify_data', 'تعديل البيانات')], help_text='نوع طلب الخدمة (مثال: المنشأة الرئيسية, المنشأة الفرعية, تعديل البيانات).', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending_review', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending_review', editable=False, help_text='الحالة الحالية لطلب الخدمة.', max_length=50),
        ),
    ]
